### ISSUE TITLE
Heap corruption in Underload (stringie.c)

### ISSUE THREAD

**Issue by stasoid** [catseye/Dipple#2]
There is currently no check if there are more than 256 characters between parens. Current implementation silently writes beyond allocated buffer (`t[j] = program[i];`) which leads to heap corruption.
Proposed fix:
replace `case '(': {...} break;` with this:
```
            case '(':
              {
                int level = 0;
                int j = 0;
                int size = 256;
                char *t = malloc(size);

                i++;
                level++;
                while (level > 0) {
                    if (program[i] == '(')
                        level++;
                    else if (program[i] == ')')
                        level--;
                    if (level > 0) {
                        t[j] = program[i];
                        j++;
                        if (j == size) {
                            size *= 2;
                            t = realloc(t, size);
                        }
                    }
                    i++;
                }
                i--;
                t[j] = '\0';
                push(t);
              }
              break;
```
What I changed:
- replaced `char *t = malloc(256);` with
```
                int size = 256;
                char *t = malloc(size);
```
- added after `j++;`
```
                        if (j == size) {
                            size *= 2;
                            t = realloc(t, size);
                        }
```

**Comment by cpressey** [comment]
Thank you for your contribution.  You are correct, there is a buffer overrun there.  The fix you suggested makes sense to me; I applied it and tested the interpreter on [the Kolakoski sequence example](http://esolangs.org/wiki/Underload#Kolakoski_sequence) and it runs for much longer than it did previously.

But what's surprising is not that the code has a bug, but that it has users.  And if it has users, it shouldn't be left to languish in this [junk drawer repo](https://github.com/search?utf8=%E2%9C%93&q=topic%3Ajunk-drawer&type=Repositories).  So, I have re-homed it to a real repo of its own:

https://github.com/catseye/stringie

and applied your suggested fix there:

https://github.com/catseye/stringie/commit/ab2446037bd98c9771c818f85773293e29bb56fd

Please feel free to close this issue if you agree this bug is fixed.

**Comment by stasoid** [comment]
Thank you
